### ISSUE TITLE
A typo in the English version, but this word is not in the doc en.js

### ISSUE THREAD

**Issue by klimgeran** [shu801115/arcana#8]
functionDeveloper 'Aecana\nDeveloper' 👉 '**Arcana**\nDeveloper'

![IMG_2863](https://user-images.githubusercontent.com/30126937/151207128-e839d712-2861-440f-ae99-db059c0d5a01.jpg)

____

If this line (between) is not added to the paragraph, this word is not translated into other languages...
<img width="376" alt="Screen Shot 2022-01-27 at 12 47 50 AM" src="https://user-images.githubusercontent.com/30126937/151208216-8e6751fe-e9e1-4c20-8d16-88a4f54bde90.png">

**Comment by shu801115** [comment]
typo was fixed & updated word list will be merged on main branch
